version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pat_db
    restart: always
    environment:
      POSTGRES_DB: pat_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pat_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: pat_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/pat_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pat_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pat_db_data:
